server:
  port: 8024

db-store: false

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/widgets
    username: sa
    password:
    driverClassName: org.h2.Driver

  flyway:
     baseline-on-migrate: true
     check-location: true
     locations: classpath:/META-INF/db/migration

controller:
  package: org.abondar.industrial.widgetstack.controller

